apiVersion: v1
kind: Service
metadata:
  name: {{ include "php-todo-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "php-todo-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "php-todo-chart.selectorLabels" . | nindent 4 }}
